# Generated by Django 4.2.13 on 2024-06-25 04:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('slug', models.SlugField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('slug', models.SlugField(max_length=555)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('subdetail', ckeditor.fields.RichTextField(blank=True)),
                ('price', models.FloatField()),
                ('former_price', models.FloatField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('num_visits', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamps', to='control.category')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
