# Generated by Django 4.2.13 on 2024-06-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_detail1',
            new_name='post_detail',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='desc_image1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='desc_image2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_detail2',
        ),
        migrations.RemoveField(
            model_name='bootcamp',
            name='description',
        ),
    ]
