# Generated by Django 4.2.13 on 2024-11-12 09:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_alter_cohort3registration_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort3registration',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://images.rawpixel.com/image_png_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw.png', max_length=255, verbose_name='image'),
        ),
    ]
