# Generated by Django 4.2.13 on 2024-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_cohort3registration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort3registration',
            name='calendar',
            field=models.FileField(blank=True, help_text='Upload course training calendar', null=True, upload_to='calendars/'),
        ),
        migrations.AddField(
            model_name='cohort3registration',
            name='scheduled_classes',
            field=models.TextField(blank=True, help_text='List of upcoming classes or assignments'),
        ),
    ]
