# Generated by Django 4.2.13 on 2024-11-12 18:39

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0029_alter_cohort3registration_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort3registration',
            name='calendar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload course training calendar', max_length=255, null=True, verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='cohort3registration',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='cohort3registration',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('instructor', 'Instructor'), ('support', 'Support Team')], max_length=10)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
