# Generated by Django 4.2.13 on 2024-06-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='doe', max_length=255)),
                ('middle_name', models.CharField(blank=True, default='jane', max_length=255, null=True)),
                ('surname', models.CharField(default='john', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('level', models.CharField(choices=[('F', 'Fresher'), ('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1)),
                ('laptop_access', models.BooleanField(default='True')),
                ('full_duration_commitment', models.BooleanField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('SM', 'Social Media'), ('FL', 'Futlink'), ('SI', 'Splash Initiative'), ('R', 'Referral'), ('N', 'NAUS'), ('O', 'Others')], max_length=2, null=True)),
                ('pledge_dedication', models.BooleanField(default='True')),
                ('pledge_terms', models.BooleanField(default='True')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.bootcamp')),
            ],
        ),
    ]
