# Generated by Django 4.2.13 on 2024-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_bootcamp_intro_alter_registration_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default='john', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_duration_commitment',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='laptop_access',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='surname',
            field=models.CharField(default='doe', max_length=255),
        ),
    ]
