# Generated by Django 4.2.13 on 2024-06-30 01:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_bootcamp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_10',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_4',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_5',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_6',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_7',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_8',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_desc_9',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_10',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_4',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_5',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_6',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_7',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_8',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='course_content_title_9',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
