# Generated by Django 4.2.13 on 2024-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_rename_post_detail1_blogpost_post_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=3700),
        ),
    ]
