# Generated by Django 4.2.13 on 2024-10-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_bootcamp_is_masterlass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootcamp',
            old_name='is_masterlass',
            new_name='is_masterclass',
        ),
    ]
