# Generated by Django 4.2.13 on 2024-10-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_alter_registration_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Enter a color code in hex format, e.g., #ff5733', max_length=7)),
            ],
        ),
    ]
