# Generated by Django 4.2.13 on 2024-10-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='control.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='color',
            field=models.CharField(choices=[('#FF5733', 'Red'), ('#33FF57', 'Green'), ('#3357FF', 'Blue'), ('#FF33A5', 'Pink'), ('#33FFF6', 'Cyan'), ('#F6FF33', 'Yellow'), ('#FF8C33', 'Orange')], help_text='Select a color', max_length=7),
        ),
    ]
