# Generated by Django 4.2.13 on 2024-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_blogpost_author_alter_author_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort3Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('laptop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('program', models.CharField(choices=[('Bootcamp', 'Bootcamp'), ('Accelerator', 'Accelerator Program'), ('Masterclass', 'Masterclass')], max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Fresher', 'Fresher'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('source', models.CharField(choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Referral', 'Referral'), ('NAUS', 'NAUS')], max_length=50)),
                ('location', models.TextField()),
                ('pledge_dedication', models.BooleanField(default='True')),
                ('course_price', models.DecimalField(decimal_places=2, default=30000, max_digits=10)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('refer_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BootcampRegistration',
        ),
    ]
