# Generated by Django 4.2.13 on 2024-11-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_cohort3registration_delete_bootcampregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='is_accelerator',
            field=models.BooleanField(default=False),
        ),
    ]
