# Generated by Django 4.2.13 on 2024-11-11 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0020_bootcamp_is_accelerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort3registration',
            name='password1',
            field=models.CharField(default='maeg242', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort3registration',
            name='password2',
            field=models.CharField(default='maega242', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort3registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort_registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohort3registration',
            name='pledge_dedication',
            field=models.BooleanField(default=True),
        ),
    ]
