# Generated by Django 4.2.13 on 2024-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_cohort3registration_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort3registration',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/image.jpg', upload_to='profile_pics/'),
        ),
    ]
