# Generated by Django 4.2.13 on 2024-11-12 17:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_cohort3registration_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort3registration',
            name='calendar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload course training calendar', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cohort3registration',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
