# Generated by Django 4.2.13 on 2024-11-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_student_project_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
