# Generated by Django 4.2.13 on 2024-11-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
