# Generated by Django 4.2.13 on 2024-11-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
