# Generated by Django 4.2.13 on 2024-11-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_ship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ship',
            new_name='DropShipping',
        ),
    ]
