# Generated by Django 4.2.13 on 2024-12-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
