# Generated by Django 4.2.13 on 2024-12-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0040_alter_contact_message_alter_contact_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dropshipping',
            name='email',
            field=models.TextField(max_length=150),
        ),
    ]
