# Generated by Django 4.2.13 on 2024-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dropshipping',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
