# Generated by Django 4.2.13 on 2024-12-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0044_alter_cohort3registration_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
